(let ((x 'outer))
	(let-syntax ((m (syntax-rules () ((m y) (list x y)))))
		(let ((x 'inner))
			(m x)
		)
	)
)

(let-syntax ((m (syntax-rules () ((m y) (let ((x 'outer)) y)))))
	(let ((x 'inner))
		(m x)
	)
)

(let-syntax ((m (syntax-rules () ((m y) (list y 'y)))))
	(m (cons 'a 'b))
)
